In [1]:
import pandas as pd
final_df = pd.read_csv(r"C:\AIML waterbourne project\final_lake_dataset.csv")
final_df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min_Nitrate_Nitrite,Min Fecal Coliform,Min Total Coliform,Year
0,LAKE,ANDHRA \nPRADESH,27,5.1,7.1,3270,1,0.65,2,800,2017
1,LAKE,ANDHRA \nPRADESH,24,5.9,6.9,597,1.3,1.16,11,350,2017
2,LAKE,ASSAM,20,2.2,5.7,50,1,0.1,300,360,2017
3,LAKE,ASSAM,22,5.1,6.6,54,0.9,0.1,300,300,2017
4,POND,ASSAM,22,0.7,6.8,263,4.5,0.8,1100,730,2017

In [2]:
final_df.shape

(2946, 11)

In [8]:
final_df['State Name'] = (
    final_df['State Name']
    .str.replace('\n', ' ', regex=False)
    .str.replace(r'\s+', ' ', regex=True)
    .str.upper()
    .str.strip()
)

final_df['State Name'].unique()

array(['ANDHRA PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH', 'CHHATTISGARH',
       'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU & KASHMIR',
       'JHARKHAND', 'KARNATAKA', 'KERALA', 'LAKSHADWEEP',
       'MADHYA PRADESH', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND',
       'ODISHA', 'PUDUCHERRY', 'PUNJAB', 'RAJASTHAN', 'TAMIL NADU',
       'TELANGANA', 'TRIPURA', 'UTTARAKHAND', 'WEST BENGAL', 'DELHI',
       'UTTAR PRADESH', 'CHANDIGAR H', 'CHHATTISGA RH', 'LAKSHADWE EP',
       'PUDUCHERR Y', 'SIKKIM', 'UTTARAKHA ND'], dtype=object)

In [4]:
san_df = pd.read_csv(r"C:\AIML waterbourne project\final sanitation cleaned_data.csv")
san_df.head()

              State  Year  Toilet_Access  Open_Defecation
0     A & N ISLANDS  2019          63.05            29.75
1   JAMMU & KASHMIR  2019          51.20            48.80
2  HIMACHAL PRADESH  2019          69.10            30.90
3            PUNJAB  2019          79.30            20.70
4        CHANDIGARH  2019          87.70            12.40

In [5]:
san_df.shape

(106, 4)

In [9]:
san_df['State'] = (
    san_df['State']
    .str.replace(r'\s+', ' ', regex=True)
    .str.upper()
    .str.strip()
)

san_df['State'].unique()

array(['A & N ISLANDS', 'JAMMU & KASHMIR', 'HIMACHAL PRADESH', 'PUNJAB',
       'CHANDIGARH', 'UTTARAKHAND', 'HARYANA', 'NCT OF DELHI',
       'RAJASTHAN', 'UTTAR PRADESH', 'BIHAR', 'SIKKIM',
       'ARUNACHAL PRADESH', 'NAGALAND', 'MANIPUR', 'MIZORAM', 'TRIPURA',
       'MEGHALAYA', 'ASSAM', 'WEST BENGAL', 'JHARKHAND', 'ODISHA',
       'CHHATTISGARH', 'MADHYA PRADESH', 'GUJARAT', 'DAMAN & DIU',
       'D & N HAVELI', 'MAHARASHTRA', 'ANDHRA PRADESH', 'KARNATAKA',
       'GOA', 'LAKSHADWEEP', 'KERALA', 'TAMIL NADU', 'PUDUCHERRY'],
      dtype=object)

In [10]:
final_df['State Name'] = final_df['State Name'].replace({
    'DELHI': 'NCT OF DELHI',
    'LAKSHADWE EP': 'LAKSHADWEEP',
    'PUDUCHERR Y': 'PUDUCHERRY',
    'CHANDIGAR H': 'CHANDIGARH',
    'CHHATTISGA RH': 'CHHATTISGARH',
    'UTTARAKHA ND': 'UTTARAKHAND'
})

final_df['State Name'].unique()

array(['ANDHRA PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH', 'CHHATTISGARH',
       'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU & KASHMIR',
       'JHARKHAND', 'KARNATAKA', 'KERALA', 'LAKSHADWEEP',
       'MADHYA PRADESH', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND',
       'ODISHA', 'PUDUCHERRY', 'PUNJAB', 'RAJASTHAN', 'TAMIL NADU',
       'TELANGANA', 'TRIPURA', 'UTTARAKHAND', 'WEST BENGAL',
       'NCT OF DELHI', 'UTTAR PRADESH', 'SIKKIM'], dtype=object)

In [11]:
print(final_df.shape)
print(san_df.shape)

(2946, 11)
(106, 4)

In [12]:
merged_df = pd.merge(
    final_df,
    san_df,
    left_on=['State Name', 'Year'],
    right_on=['State', 'Year'],
    how='left'
)

merged_df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min_Nitrate_Nitrite,Min Fecal Coliform,Min Total Coliform,Year,State,Toilet_Access,Open_Defecation
0,LAKE,ANDHRA PRADESH,27,5.1,7.1,3270,1,0.65,2,800,2017,NaN,NaN,NaN
1,LAKE,ANDHRA PRADESH,24,5.9,6.9,597,1.3,1.16,11,350,2017,NaN,NaN,NaN
2,LAKE,ASSAM,20,2.2,5.7,50,1,0.1,300,360,2017,NaN,NaN,NaN
3,LAKE,ASSAM,22,5.1,6.6,54,0.9,0.1,300,300,2017,NaN,NaN,NaN
4,POND,ASSAM,22,0.7,6.8,263,4.5,0.8,1100,730,2017,NaN,NaN,NaN

In [13]:
print(merged_df.shape)

print(merged_df.columns)

merged_df.isnull().sum()

(3788, 14)
Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min pH', 'Min Conductivity', 'Min BOD',
       'Min_Nitrate_Nitrite', 'Min Fecal Coliform', 'Min Total Coliform',
       'Year', 'State', 'Toilet_Access', 'Open_Defecation'],
      dtype='object')

Type Water Body            0
State Name                 0
Min Temperature            0
Min Dissolved Oxygen       0
Min pH                     0
Min Conductivity           0
Min BOD                    0
Min_Nitrate_Nitrite        0
Min Fecal Coliform         0
Min Total Coliform         0
Year                       0
State                   2525
Toilet_Access           2525
Open_Defecation         2525
dtype: int64

In [14]:
merged_df['Toilet_Access'] = (
    merged_df.groupby('State Name')['Toilet_Access']
    .transform(lambda x: x.ffill().bfill())
)

merged_df['Open_Defecation'] = (
    merged_df.groupby('State Name')['Open_Defecation']
    .transform(lambda x: x.ffill().bfill())
)

merged_df.isnull().sum()

Type Water Body            0
State Name                 0
Min Temperature            0
Min Dissolved Oxygen       0
Min pH                     0
Min Conductivity           0
Min BOD                    0
Min_Nitrate_Nitrite        0
Min Fecal Coliform         0
Min Total Coliform         0
Year                       0
State                   2525
Toilet_Access            539
Open_Defecation          539
dtype: int64

In [15]:
missing_states = merged_df[merged_df['Toilet_Access'].isnull()]['State Name'].unique()

missing_states

array(['TELANGANA', 'SIKKIM'], dtype=object)

In [16]:
merged_df['Toilet_Access'] = merged_df['Toilet_Access'].fillna(
    merged_df['Toilet_Access'].mean()
)

merged_df['Open_Defecation'] = merged_df['Open_Defecation'].fillna(
    merged_df['Open_Defecation'].mean()
)

merged_df.isnull().sum()

Type Water Body            0
State Name                 0
Min Temperature            0
Min Dissolved Oxygen       0
Min pH                     0
Min Conductivity           0
Min BOD                    0
Min_Nitrate_Nitrite        0
Min Fecal Coliform         0
Min Total Coliform         0
Year                       0
State                   2525
Toilet_Access              0
Open_Defecation            0
dtype: int64

In [17]:
merged_df.drop(columns=['State'], inplace=True)

merged_df.isnull().sum()

Type Water Body         0
State Name              0
Min Temperature         0
Min Dissolved Oxygen    0
Min pH                  0
Min Conductivity        0
Min BOD                 0
Min_Nitrate_Nitrite     0
Min Fecal Coliform      0
Min Total Coliform      0
Year                    0
Toilet_Access           0
Open_Defecation         0
dtype: int64

In [18]:
merged_df.to_csv(
    r"C:\AIML waterbourne project\merged_water_sanitation.csv",
    index=False
)

print("Merged dataset saved successfully!")

Merged dataset saved successfully!