In [3]:
import pandas as pd
env_df = pd.read_csv(
    r"C:\AIML waterbourne project\clean environment_data.csv")
env_df.head()

               State    Rainfall  Year
0  ANDAMAN & NICOBAR    0.000000  2019
1     ANDHRA PRADESH   80.778387  2019
2  ARUNACHAL PRADESH  219.886151  2019
3              ASSAM  201.048883  2019
4              BIHAR   82.782091  2019

In [4]:
print(env_df.shape)

print(env_df.columns)

env_df.isnull().sum()

(37, 3)
Index(['State', 'Rainfall', 'Year'], dtype='object')

State       0
Rainfall    0
Year        0
dtype: int64

In [5]:
env_df['State'] = (
    env_df['State']
    .str.replace(r'\s+', ' ', regex=True)
    .str.upper()
    .str.strip()
)

env_df['State'].unique()

array(['ANDAMAN & NICOBAR', 'ANDHRA PRADESH', 'ARUNACHAL PRADESH',
       'ASSAM', 'BIHAR', 'CHANDIGARH', 'CHHATTISGARH',
       'DADRA & NAGAR HAVELI', 'DAMAN & DIU', 'DELHI', 'GOA', 'GUJARAT',
       'HARYANA', 'HIMACHAL PRADESH', 'JAMMU & KASHMIR', 'JHARKHAND',
       'KARNATAKA', 'KERALA', 'LADAKH', 'LAKSHADWEEP', 'MADHYA PRADESH',
       'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND',
       'ODISHA', 'PUDUCHERRY', 'PUNJAB', 'RAJASTHAN', 'SIKKIM',
       'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH',
       'UTTARAKHAND', 'WEST BENGAL'], dtype=object)

In [6]:
main_df = pd.read_csv(
    r"C:\AIML waterbourne project\merged_water_sanitation.csv"
)

main_df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min_Nitrate_Nitrite,Min Fecal Coliform,Min Total Coliform,Year,Toilet_Access,Open_Defecation
0,LAKE,ANDHRA PRADESH,27,5.1,7.1,3270,1,0.65,2,800,2017,49.6,50.4
1,LAKE,ANDHRA PRADESH,24,5.9,6.9,597,1.3,1.16,11,350,2017,49.6,50.4
2,LAKE,ASSAM,20,2.2,5.7,50,1,0.1,300,360,2017,65.0,35.1
3,LAKE,ASSAM,22,5.1,6.6,54,0.9,0.1,300,300,2017,65.0,35.1
4,POND,ASSAM,22,0.7,6.8,263,4.5,0.8,1100,730,2017,65.0,35.1

In [7]:
main_df['State Name'].unique()

array(['ANDHRA PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH', 'CHHATTISGARH',
       'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU & KASHMIR',
       'JHARKHAND', 'KARNATAKA', 'KERALA', 'LAKSHADWEEP',
       'MADHYA PRADESH', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND',
       'ODISHA', 'PUDUCHERRY', 'PUNJAB', 'RAJASTHAN', 'TAMIL NADU',
       'TELANGANA', 'TRIPURA', 'UTTARAKHAND', 'WEST BENGAL',
       'NCT OF DELHI', 'UTTAR PRADESH', 'SIKKIM'], dtype=object)

In [8]:
final_merged_df = pd.merge(
    main_df,
    env_df,
    left_on=['State Name', 'Year'],
    right_on=['State', 'Year'],
    how='left'
)

final_merged_df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min_Nitrate_Nitrite,Min Fecal Coliform,Min Total Coliform,Year,Toilet_Access,Open_Defecation,State,Rainfall
0,LAKE,ANDHRA PRADESH,27,5.1,7.1,3270,1,0.65,2,800,2017,49.6,50.4,NaN,NaN
1,LAKE,ANDHRA PRADESH,24,5.9,6.9,597,1.3,1.16,11,350,2017,49.6,50.4,NaN,NaN
2,LAKE,ASSAM,20,2.2,5.7,50,1,0.1,300,360,2017,65.0,35.1,NaN,NaN
3,LAKE,ASSAM,22,5.1,6.6,54,0.9,0.1,300,300,2017,65.0,35.1,NaN,NaN
4,POND,ASSAM,22,0.7,6.8,263,4.5,0.8,1100,730,2017,65.0,35.1,NaN,NaN

In [9]:
print(final_merged_df.shape)

final_merged_df.isnull().sum()

(3788, 15)

Type Water Body            0
State Name                 0
Min Temperature            0
Min Dissolved Oxygen       0
Min pH                     0
Min Conductivity           0
Min BOD                    0
Min_Nitrate_Nitrite        0
Min Fecal Coliform         0
Min Total Coliform         0
Year                       0
Toilet_Access              0
Open_Defecation            0
State                   2458
Rainfall                2458
dtype: int64

In [10]:
final_merged_df['Rainfall'] = (
    final_merged_df.groupby('State Name')['Rainfall']
    .transform(lambda x: x.ffill().bfill())
)

final_merged_df.isnull().sum()

Type Water Body            0
State Name                 0
Min Temperature            0
Min Dissolved Oxygen       0
Min pH                     0
Min Conductivity           0
Min BOD                    0
Min_Nitrate_Nitrite        0
Min Fecal Coliform         0
Min Total Coliform         0
Year                       0
Toilet_Access              0
Open_Defecation            0
State                   2458
Rainfall                  22
dtype: int64

In [11]:
missing_rainfall_states = final_merged_df[
    final_merged_df['Rainfall'].isnull()
]['State Name'].unique()

missing_rainfall_states

array(['NCT OF DELHI', 'SIKKIM'], dtype=object)

In [12]:
final_merged_df['Rainfall'] = final_merged_df['Rainfall'].fillna(
    final_merged_df['Rainfall'].mean()
)

final_merged_df.isnull().sum()

Type Water Body            0
State Name                 0
Min Temperature            0
Min Dissolved Oxygen       0
Min pH                     0
Min Conductivity           0
Min BOD                    0
Min_Nitrate_Nitrite        0
Min Fecal Coliform         0
Min Total Coliform         0
Year                       0
Toilet_Access              0
Open_Defecation            0
State                   2458
Rainfall                   0
dtype: int64

In [13]:
final_merged_df.drop(columns=['State'], inplace=True)

final_merged_df.isnull().sum()

Type Water Body         0
State Name              0
Min Temperature         0
Min Dissolved Oxygen    0
Min pH                  0
Min Conductivity        0
Min BOD                 0
Min_Nitrate_Nitrite     0
Min Fecal Coliform      0
Min Total Coliform      0
Year                    0
Toilet_Access           0
Open_Defecation         0
Rainfall                0
dtype: int64

In [ ]:
final_merged_df.to_csv(
    r"C:\AIML waterbourne project\final_complete_dataset.csv",
    index=False
)

print("Final dataset saved successfully!")

Final dataset saved successfully!